### ISSUE TITLE
Text position is lost randomly

### ISSUE THREAD

**Issue by capvor** [spakin/SimpInkScr#74] opened 2023-02-11 16:33 UTC
I have a script that draws some graphics and text, but the position of some text is randomly lost. High probability of recurrence.

here is my script: 
[draw.zip](https://github.com/spakin/SimpInkScr/files/10714094/draw.zip)

This is the normal case for drawing:
![image](https://user-images.githubusercontent.com/16610170/218269456-8ffc1061-b85f-48bf-a0fb-d9f26e941e66.png)

This is the two problematic drawing:
![image](https://user-images.githubusercontent.com/16610170/218269251-d3027368-d36f-4453-b0ff-4ef2e0f74ff5.png)

![image](https://user-images.githubusercontent.com/16610170/218269350-5fe89391-69bc-4b02-a488-029745c00b8a.png)

**Comment by capvor** [comment] 2023-02-11 16:34
My Inkscape version is `Inkscape 1.2.2 (732a01da63, 2022-12-09)`
Simple Inkscape Scripting version is `v3.2.0`

**Comment by spakin** [comment] 2023-02-13 01:17
Thanks for the bug report and especially for providing a script that can be used for testing.  The good news is that I can (occasionally) reproduce the problem.  The bad news is that I'm baffled as to what can be causing the problem or how to fix it.  It definitely appears that Inkscape, rather than Simple Inkscape Scripting, is the culprit, however.

**Comment by spakin** [comment] 2023-02-18 23:23
The Inkscape team confirms that this is a bug in Inkscape!  See Inkscape issue [#4102](https://gitlab.com/inkscape/inkscape/-/issues/4102), "Race condition in inkex.command.inkscape".

Once again, thanks for the bug report.  I'm closing this issue as we now know the problem is not specific to Simple Inkscape Scripting.

**Closed by spakin** 2023-02-18 23:23 UTC

**Comment by capvor** [comment] 2023-02-24 04:37
I am very sorry, I have been busy recently and have not paid attention to GitHub. 
Thank you very much for your research on this issue.
