### ISSUE TITLE
error on my mac while running the simple circle example

### ISSUE THREAD

**Issue by InesSchneiderOAL** [spakin/SimpInkScr#8] opened 2021-11-30 10:35 UTC
I get this error message: (extensions folder is on chmod 755)

Traceback (most recent call last):
  File "simple_inkscape_scripting.py", line 24, in <module>
    import PIL.Image
ModuleNotFoundError: No module named 'PIL'

**Comment by Viljen789** [comment] 2021-11-30 13:16
me too

**Comment by spakin** [comment] 2021-11-30 17:44
PIL (now superceded by the fully compatible [Pillow](https://pillow.readthedocs.io/)) is the Python Imaging Library.  It's needed by Simple Inkscape Scripting to handle the `image` function.  I had thought Pillow was commonly included with most Python distributions, but that's apparently not the case on macOS.

Does the command
```bash
pip3 install Pillow
```
resolve the missing module?

**Comment by Viljen789** [comment] 2021-11-30 18:05
I’ve tried to run the code in the terminal, no success. I use anaconda (spyder) is this a problem? Also, couldn’t resolve the problem in VCS. The VSC IDE aswell as the spyder IDE instead Of vcs, tried the command in the terminal using
both pip3 and pip
i believe theres a problem in the fact that im
using a conda environment, could this be the
case? Any advise?

**Comment by spakin** [comment] 2021-11-30 18:48
I don't *think* anaconda should pose a problem as long as you launch Inkscape from that environment.

Does `python -m PIL` give you a page of information about PIL features?  That at least confirms that PIL is installed.

**Comment by Viljen789** [comment] 2021-12-01 15:05
Yeah, python -m PIL brings up the page with information

**Comment by spakin** [comment] 2021-12-01 15:57
Okay, good.  What happens when you launch Inkscape from that shell?  Do you still get the error message about PIL?

**Comment by spakin** [comment] 2021-12-01 21:59
It's possible to tell Inkscape what Python executable to use when running Python extensions.  See https://wiki.inkscape.org/wiki/Extension_Interpreters.  Does it help to point that to your anaconda version?

**Comment by Viljen789** [comment] 2021-12-02 07:03
I can't find anything that solves the problem in the link.

**Comment by Viljen789** [comment] 2021-12-02 08:34
> It's possible to tell Inkscape what Python executable to use when running Python extensions. See https://wiki.inkscape.org/wiki/Extension_Interpreters. Does it help to point Inkscape to your anaconda version of Python?

After totally uninstalling Anaconda and reinstalling Python on the computer (attempting to only use Python without Anaconda for now), I discovered that Mac OS has Python in PATH already, and that it's not removable. This wouldn't be an issue, however it seems to be colliding with my Python3.10 install. I tried running a script in Visual Studio Code where I simply imported Pillow after installing it through pip3 and it worked. This leads me to believe that your extension is running on my Mac OS version of python. I tried running a simple code in your script and got this error:

`Traceback (most recent call last):
  File "simple_inkscape_scripting.py", line 24, in <module>
    import Pillow
ModuleNotFoundError: No module named 'Pillow'
`

I tried adding the python-interpreter parameter in the preferences.xml file you showed me earlier, but it still didn't work. Any thoughts?

**Comment by spakin** [comment] 2021-12-02 14:27
> I tried adding the python-interpreter parameter in the preferences.xml file you showed me earlier, but it still didn't work. Any thoughts?

So even pointing `python-interpreter` to the full path of your Python 3.10 install still runs the macOS version of Python?  To verify, what happens if you set `python-interpreter` to, say, `/bin/false`?  Does that at least cause nothing to happen (or give a different error message)?

(Be sure to re-launch Inkscape after editing `preferences.xml` so it recognizes the change.)

**Comment by Viljen789** [comment] 2021-12-02 20:29
> > I tried adding the python-interpreter parameter in the preferences.xml file you showed me earlier, but it still didn't work. Any thoughts?
> 
> So even pointing `python-interpreter` to the full path of your Python 3.10 install still runs the macOS version of Python? To verify, what happens if you set `python-interpreter` to, say, `/bin/false`? Does that at least cause nothing to happen (or give a different error message)?
> 
> (Be sure to re-launch Inkscape after editing `preferences.xml` so it recognizes the change.)

Well, this seems to be where the issue is located. After adding the parameter nothing seems to be working. I tried changing it to /bin/false and still getting the same error. Perhaps I set up the XML file wrong? Here's what I have:
`  </group>
  <group
     id="extensions"
     python-interpreter="$HOME/Applications/python3.10"
     org.inkscape.input.svg.scale="auto"
     org.pakin.filter.simple_inkscape_scripting.tab="Code"
     org.pakin.filter.simple_inkscape_scripting.program="circle(5, 100, 50)\n" />
  <group
     id="desktop"
     style="">'
Do you see any typos or misconceptions? Could also attach the entire .XML file if required.

**Comment by spakin** [comment] 2021-12-03 03:30
I would be surprised if Inkscape expanded `$HOME` automatically.  It might be safer to spell out the full filename for your Python interpreter.  Other than that, I don't see any obvious problems with what you tried.

I set `python-interpreter="/bin/false"`, and, as expected, running a Simple Inkscape Scripting script did nothing so Inkscape does appear to honor that option.  Try using
```Python
print(sys.executable)
```
as your Simple Inkscape Scripting script to test if Inkscape is picking up the correct program.

**Comment by Viljen789** [comment] 2021-12-03 12:49
> I would be surprised if Inkscape expanded `$HOME` automatically. It might be safer to spell out the full filename for your Python interpreter. Other than that, I don't see any obvious problems with what you tried.
> 
> I set `python-interpreter="/bin/false"`, and, as expected, running a Simple Inkscape Scripting script did nothing so Inkscape does appear to honor that option. Try using
> 
> ```python
> print(sys.executable)
> ```
> 
> as your Simple Inkscape Scripting script to test if Inkscape is picking up the correct program.

Hey! After trying this, I am getting a new error! (I guess it's good.) I ran a simple circle() example. I changed the python interpreter to python-interpreter="/usr/local/bin/python3.10"
`Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/SimpInkScr/simple_inkscape_scripting.py", line 23, in <module>
    import inkex
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/__init__.py", line 17, in <module>
    from .extensions import *
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/extensions.py", line 33, in <module>
    from .elements import load_svg, BaseElement, ShapeElement, Group, Layer, Grid, \
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/__init__.py", line 9, in <module>
    from ._base import SVG_PARSER, load_svg, ShapeElement, BaseElement
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
`

**Comment by InesSchneiderOAL** [comment] 2021-12-03 13:06
Thanks for all the answers. But I think the mac version of inscape is not quite stable. There are so many other issues with this mac version and the only solution is restart or going to the win version. There your interpreter works brilliant. For my mac, I tried to compile a fresh git source code with homebrew C++, but even there the cmake script is not really up to date with the modules needed, like lipsoup. Seams, that Inkscape is not very interested in the mac users.

**Comment by Viljen789** [comment] 2021-12-03 14:10
Ok, thanks. That really sucks then, to not include mac users.

**Comment by spakin** [comment] 2021-12-03 23:59
> "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/inkex/elements/_base.py", line 31, in <module> from lxml import etree ModuleNotFoundError: No module named 'lxml'

It sounds like `/usr/local/bin/python3.10` can't find the `lxml` XML library.  Does
```bash
/usr/local/bin/python3.10 -m pip show lxml
```
provide information or an error message?  If it's the former, try installing `lxml`,
```bash
/usr/local/bin/python3.10 -m pip install lxml
```
and seeing if Inkscape can finally run Simple Inkscape Scripting.

**Comment by Viljen789** [comment] 2021-12-04 08:23
I installed lxml first, then when I ran the first line it it gave information, no error. I ran both codes through the mac terminal. When trying to run code directly from inkscape, or importing another file from the mac I once again encounter the error: 

`Traceback (most recent call last):
  File "/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions/SimpInkScr/simple_inkscape_scripting.py", line 24, in <module>
    import Pillow
ModuleNotFoundError: No module named 'Pillow'
`
Did I install it wrong?

**Comment by spakin** [comment] 2021-12-04 18:09
If you're no longer getting the `No module named 'lxml'` error, we may be making progress.  Does
```bash
/usr/local/bin/python3.10 -m pip install PIL
```
finally make everything work?

**Comment by Viljen789** [comment] 2021-12-05 16:39
> ```shell
> /usr/local/bin/python3.10 -m pip install PIL
> ```

I still get an error:
```
ERROR: Could not find a version that satisfies the requirement PIL (from versions: none)
ERROR: No matching distribution found for PIL

```

**Comment by spakin** [comment] 2021-12-05 17:09
I should have specified Pillow, a replacement for the now-unmaintained PIL:
```bash
/usr/local/bin/python3.10 -m pip install Pillow
```
Any luck with that?

**Comment by Viljen789** [comment] 2021-12-05 17:31
Oh, ok. 
I think it is already installed:

( `Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (8.4.0)` )

**Comment by spakin** [comment] 2021-12-05 21:09
But you're still getting a `No module named 'Pillow'` error when you run Simple Inkscape Scripting?  What does
```bash
echo $PYTHONPATH
```
output?

**Comment by Viljen789** [comment] 2021-12-06 07:21
Yes, i still get "no module named pillow". 

When trying:


> ```shell
> echo $PYTHONPATH
> ```

I don't get any output when running it in the terminal. Any ideas?

**Comment by Viljen789** [comment] 2021-12-06 07:29
> But you're still getting a `No module named 'Pillow'` error when you run Simple Inkscape Scripting? What does
> 
> ```shell
> echo $PYTHONPATH
> ```
> 
> output?

I ran the command `echo $PATH` and got the following output:
`/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin`

**Comment by Parchedd** [comment] 2021-12-06 07:32
> >

Since this command isn't giving output, would it be possible to use the sys module? IIRC, the sys module should be based on the PYTHONPATH variable.

**Comment by spakin** [comment] 2021-12-06 23:56
> Since this command isn't giving output, would it be possible to use the sys module, @spakin? IIRC, the sys module should be based on the PYTHONPATH variable.

@Parchedd: I mostly wanted to know if the problem was due to the shell having `PYTHONPATH` set but Inkscape seeing it unset.  Given that it's unset in the shell, too, Inkscape *shouldn't* have a problem.

@Viljen789: Could you please confirm that

1. you included `python-interpreter="/usr/local/bin/python3.10"` in your `preferences.xml` file,
2. `/usr/local/bin/python3.10 -c 'import lxml; import PIL.Image'` returns with no error message, and
3. you didn't edit `simple_inkscape_scripting.py` while debugging and forget to change it back?

**Comment by spakin** [comment] 2021-12-08 03:43
What I don't understand is why the error message would be "No module named **Pillow**" instead of "No module named **PIL**".  Simple Inkscape Scripting does an `import PIL.Image`; Pillow is just the replacement implementation of PIL.

Can you run Simple Inkscape Scripting from the command line?
```bash
env PYTHONPATH=/usr/share/inkscape/extensions:$PYTHONPATH /usr/local/bin/python3.10 $HOME/.config/inkscape/extensions/simple_inkscape_scripting/simple_inkscape_scripting.py --py-source=$HOME/.config/inkscape/extensions/simple_inkscape_scripting/examples/binary_tree.py --output=my-output.svg /usr/share/inkscape/templates/default.svg
```
(You'll need to update the paths in the above to match your installation locations, but the above illustrates the basic idea.)  If that works, it suggests that the problem is with the way Inkscape is launching Simple Inkscape Scripting.  If it gives an error message, that suggests that the problem may be with the Python installation.

**Comment by Viljen789** [comment] 2021-12-09 08:07
I switched over to a windows PC to avoid the problem. Thanks a lot for all the help, I really appreciate it!

**Comment by spakin** [comment] 2021-12-09 08:17
Thanks for letting me know.  It's disappointing we weren't able to get Simple Inkscape Scripting working on your Mac, though.  I'll close the issue now.

**Closed by spakin** 2021-12-09 08:17 UTC
